name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-all-microservices:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Esto buscar치 todas las carpetas que comiencen con ms- y las procesar치 en paralelo
        microservice: [ms-holamundo, ms-inventario]
        # Nota: Puedes generar esta lista din치micamente con un paso previo si prefieres
    
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.microservice }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesi칩n en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir la imagen de Docker
        run: |
          docker build -t $IMAGE_NAME backend/${{ matrix.microservice }}

      - name: Enviar la imagen a Docker Hub
        run: docker push $IMAGE_NAME